#!/usr/bin/env bash

ssh ubuntu@100.26.238.37 -i ~/.ssh/school
mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys
chmod 700 ~/.ssh && chmod 600 ~/.ssh/authorized_keys
echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtoSjR6rxMXyt10Ynxw32Hq2G6PeTkAWl8ND7nUoIBp4b24oRhmYa4mvxG0Bmo0HfA+Cozigklzp9JHPugWZFFK2W0ySzH99lSrQG3fYJH4Ab7muP62T/XleAGw05I2F/QphLeQihwaxA6ux7Qqmf5SO6Ox0rAsFxvWqDegxYzPC4uWuM/zZeraSd0Se9M1m/iXtcKT+4vqgci/WTL3JTLUDVpLDYnck3pXHkSrZtQFQDBaL/Mo8gPbC25PzPtbJrSyIkpf9EPQG1fIcpVHQiU/yqRz9G3pJjL58bSuqx0xn5m49FSPOOl+vr1I0DWIhVN0SZ3RqVYYpXwblYHJbTSXjzhCWMFKxLI+x/LB0uOMitQTqrXvgen2iPpU5T4fdScnAEdbIy9RSR423XAbV6UdCXKe7UUM0bnu1PHLxKoDtvuAECiQ72poiHjuFcMF0Wsfnqp5w15Jz885HyVhZX/wmi1mMQKIgdD+xhaDszSskMM5r7J6oJxTjZh0yrqM2E= user@DESKTOP-84868SL
